"""add param templates and custom agents

Revision ID: 7d2a9f4e3c1b8a50
Revises: a305ff3510ea
Create Date: 2026-08-14 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2a9f4e3c1b8a50'
down_revision: Union[str, Sequence[str], None] = 'a305ff3510ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('param_schema', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_agents_key'), 'custom_agents', ['key'], unique=True)
    op.create_index(op.f('ix_custom_agents_tenant_id'), 'custom_agents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_custom_agents_user_id'), 'custom_agents', ['user_id'], unique=False)
    op.create_table('param_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('agent_key', sa.String(length=80), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_param_templates_agent_key'), 'param_templates', ['agent_key'], unique=False)
    op.create_index(op.f('ix_param_templates_tenant_id'), 'param_templates', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_param_templates_user_id'), 'param_templates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_param_templates_user_id'), table_name='param_templates')
    op.drop_index(op.f('ix_param_templates_tenant_id'), table_name='param_templates')
    op.drop_index(op.f('ix_param_templates_agent_key'), table_name='param_templates')
    op.drop_table('param_templates')
    op.drop_index(op.f('ix_custom_agents_user_id'), table_name='custom_agents')
    op.drop_index(op.f('ix_custom_agents_tenant_id'), table_name='custom_agents')
    op.drop_index(op.f('ix_custom_agents_key'), table_name='custom_agents')
    op.drop_table('custom_agents')
    # ### end Alembic commands ###
